# Generated by Django 4.2.11 on 2024-03-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=250)),
                ('weight', models.FloatField()),
                ('color', models.CharField(max_length=20)),
                ('shipment_fee', models.FloatField()),
                ('manufacturer', models.CharField(max_length=20)),
                ('warranty', models.IntegerField()),
            ],
        ),
    ]
