# Generated by Django 4.2.11 on 2024-03-11 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeAppliance', '0004_alter_cart_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeAppliance.cart'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeAppliance.product'),
        ),
    ]
