# Generated by Django 4.2.11 on 2024-03-07 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('image', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.item')),
            ],
        ),
    ]
